version: '3.4'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "TestMeister:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  spark-master:
    container_name: spark-master
    image: spark
    build:
      context: ./services/spark
      dockerfile: Dockerfile
    command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
    hostname: spark-master
    environment:
      MASTER: spark://spark-master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: localhost
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    volumes:
      - ./services/spark/conf/master:/conf
      - ./services/spark/data:/tmp/data
  spark-worker:
    image: spark
    container_name: spark-worker
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    hostname: spark-worker
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    ports:
      - 8081:8081
    volumes:
      - ./services/spark/conf/worker:/conf
      - ./services/spark/data:/tmp/data
    links:
      - spark-master
    depends_on:
      - spark-master
  nudge-server:
    restart: always
    image: nudge-server
    build:
      context: ./services/nudge_server
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    command: hypercorn -b 0.0.0.0 server:app
    environment:
      - PYTHONUNBUFFERED=0
    env_file:
      - .env
  nudge-client:
    image: nudge-client
    build:
      context: ./services/nudge_client
      dockerfile: Dockerfile
    volumes:
      - './services/nudge_client:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
  quart-nginx:
    image: quart-nginx
    build:
      context: ./services
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    links:
      - nudge-server
    depends_on:
      - nudge-server
